### ISSUE TITLE
rhcloud avocado repo isn't available

### ISSUE THREAD

**Issue by amoskong** [avocado-framework/avocado-ec2#4]
https://repos-avocadoproject.rhcloud.com/static/avocado-el.repo
https://repos-avocadoproject.rhcloud.com/static/avocado-fedora.repo

In avocado_ec2/plugins/ec2.py, we are trying to install avocado from rhcloud repo, but it's unavailable now.

A tmp solution is installing avocado from pip:

`sudo yum install -y gcc openssl-devel python-devel python2-pip libvirt libvirt-devel pkgconfig gdb-gdbserver git; sudo pip install -r https://raw.githubusercontent.com/avocado-framework/avocado/36lts/requirements.txt; sudo pip install avocado-framework==36.4`

**Comment by ldoktor** [comment]
Hello @amoskong, the `rhcloud` repo was discontinued and we moved all assets to http://avocado-project.org

there is one cons @clebergnu is working on and that is the lack of `https`. Anyway (hopefully) all links were updated in documentation before the shutdown so you can check it there...

**Comment by amoskong** [comment]
Yes the latest doc and new repo are fine. But we currently uses rhcloud repo in avocado-ec2 project, need to fix it.
