### ISSUE TITLE
Time to archive this repository?

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado-ec2#9]
Should we archive this repository? This plugin isn’t actively developed anymore (last commit was almost 3 years ago) and installation has been broken for some time now. All the remote repositories listed in `ec2.py` in launchpad and https://avocado-project.org/data/repos/ are not available or out of date.

cc:
@lmr @amoskong @ldoktor

**Comment by amoskong** [comment]
The avocado-ec2 was replaced by boto3 in ScyllaDB, I'm ok to archive this repo.

**Comment by lmr** [comment]
As much as I'd love to give this plugin some maintenance, I'm afraid I won't have time to maintain it.

I'm also OK with archiving the repo.

**Comment by ana** [comment]
Thanks for the replies! I'll leave some time in case somebody else has comments and I'll archive this on October 18.

**Comment by ana** [comment]
Time to archive this repository.
